### ISSUE TITLE
What is rockspec-reboot? / Documentation request

### ISSUE THREAD

**Issue by cxw42** [gvvaughan/luke#2]
Gary, I ran across `luke` in the luaposix package, and I see rockspec-reboot is very different from master.  I am intrigued by the ideas in master:README.md.  Is rockspec-reboot along similar lines?  Would you be willing to add some documentation to rockspec-reboot to explain the direction you're taking?  Thanks!

**Comment by gvvaughan** [comment]
Hey Chris,

Thanks for your interest. The reboot branch is very much in flux right now, so I don't have enough of an idea of the final shape it will take to write a README that is not just fluff.

But I'll give you a tentative roadmap here instead :-)

The idea in the first instance is to work out what additions are needed to the existing rockspec format in order to support the autoconf-like features required to build luaposix, lyaml, and the like. I'm working out the details in the lukefile, and planning to contribute the format changes and build time improvements back to luarocks-3.

With that done, I'd like to retrofit some of the nice features from master into the rockspec driven format. That way luke will be able to build projects that have adopted the enhanced rockspec format from just the existing project rockspec, and non-lua based projects will be able to specific the build from a lukefile with the additional features I outlined in the master README.

Suggestions and contributions are more than welcome!

Cheers,
Gary

**Comment by cxw42** [comment]
Gary, thanks very much for the explanation!  I will close this item.
